apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    spec:
      volumes:
        - name: nfs
          persistentVolumeClamin:
            claimName: manual-pvc
      containers:
        - name: app
          image: aaaa
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: nfs
              mountPath: "/usr/share/data"