apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypv1
spec:
  storageClassName: nfs # pv 的分类， gfs
  persistentVolumeReclaimPolicy: Recycle # Retain: 手工回收，Recycle：清除PV的数据， Delete：删除对应的存储资源
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany # ReadWriteOnce: 单个节点读写， ReadOnlyMany : 多个节点读， ReadWriteMany: 多个节点读写
  nfs:
    server: 192.168.0.22
    path: "/nfs/dd"
